### ISSUE TITLE
PureScript comments shouldn't have HTML

### ISSUE THREAD

**Issue by plippe** [purescript-aws-sdk/gen#3]
aws-sdk-js has documentation for certain fields. Those contain HTML/XML tags. These tags are displayed as plain text on pursuit.

Remove those tags from the comments.

**Comment by paf31** [comment]
Thanks for working on this project! 

I assume these comments are generated from something else? Since the docs are hosted on Pursuit, it would be good if the LICENSE for the original documentation could be indicated there somehow as well.

**Comment by plippe** [comment]
Hi,

All of this is generated from the official aws-sdk-js. There is a link to it in the README.md. It has an Apache License 2.0, will have a look to see if I need to update anything.

**Comment by plippe** [comment]
Added Notice based on Apache requirement: https://github.com/purescript-aws-sdk/gen/compare/aws-sdk-notice?expand=1

**Comment by plippe** [comment]
Documentation hosted on S3. Html is rendered properly.
