### ISSUE TITLE
Removal from Pursuit

### ISSUE THREAD

**Issue by paf31** [purescript-aws-sdk/gen#32]
Sorry, but I had to remove the docs for these packages from Pursuit because they were causing too much memory overhead. I suggest running a separate instance if you need search, or even just generating and hosting the HTML docs using `purs docs`.

**Comment by plippe** [comment]
Hi,

Really sorry for the inconvenience. I will remove all the code hitting your services and host the documentation on GitHub. 

Sorry again

**Comment by paf31** [comment]
No problem! Just wanted to give you an explanation why.
