### ISSUE TITLE
Better default values and helpers

### ISSUE THREAD

**Issue by plippe** [purescript-aws-sdk/gen#38]
Use [`over`](https://pursuit.purescript.org/packages/purescript-newtype/2.0.0/docs/Data.Newtype#v:over) to allow updates of default values instead of building the full object from scratch each time.

```purescript
defaultValue :: Value
defaultValue = Value
    { a: NullOrUndefined Nothing
    , b: NullOrUndefined Nothing
    }

defaultValue' :: (ValueType -> ValueType) -> Value
defaultValue' f = over Value f defaultValue
```

**Comment by jvliwanag** [comment]
Let's use Union instead for this similar to purescript-aws-sdk/purescript-aws-request#38
